### ISSUE TITLE
Just upgraded to 1.4.0 and previously working boolean arg (--wait) now fails

### ISSUE THREAD

**Issue by eric-swann-q2** [widdix/cfn-create-or-update#13]
Running a script with --wait after upgrade to 1.4.0 gives the following result.  No issues running this command in 1.3.0.

Command:
`cfn-create-or-update --stack-name whatever --template-body file://dist/cloud-formation/thing.yml --capabilities CAPABILITY_NAMED_IAM --wait`

also tried `--wait true` and `--wait "true"`

All returned the same error.

```
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/cfn-create-or-update/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/cfn-create-or-update/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (<anonymous>)
    at argsert (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/cfn-create-or-update/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/cfn-create-or-update/node_modules/yargs/yargs.js:778:5)
    at Object.exports.parse (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/cfn-create-or-update/lib/arg.js:28:6)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/cfn-create-or-update/cli.js:20:30)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by CallumHibbert** [comment]
Came here to say the same thing. This is a really useful package and its nice to see it updated but I've had to lock it to v1.3.0 for now. The "wait" option is a key use case for me. Thanks.

**Comment by michaelwittig** [comment]
can you test `1.4.1`?

**Comment by eric-swann-q2** [comment]
Sorry, I missed the response.  I'll try upgrading to 1.5 and see what happens.
