### ISSUE TITLE
Is there any way to reuse the existing parameters when updating?

### ISSUE THREAD

**Issue by gurumark** [widdix/cfn-create-or-update#7]
I am getting the following:
cfn-create-or-update --stack-name wordpress-ha --template-body file://wordpress-ha-aurora.yaml --region us-east-1
Parameters: [BlogAdminPassword, DomainName, ParentVPCStack, CloudFrontAcmCertificate, BlogAdminEMail, ElbAcmCertificate] must have values ValidationError: Parameters: [BlogAdminPassword, DomainName, ParentVPCStack, CloudFrontAcmCertificate, BlogAdminEMail, ElbAcmCertificate] must have values
    at Request.extractError (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/usr/local/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
****
I guess it's asking to provide the required parameters. Is there any option to pass the option such "use the existing ones"?

**Comment by michaelwittig** [comment]
Hi @gurumark 
since this tool performs create or update, you always have to specify the parameters because you don't know if it will be a create or update upfront. Does this make sense?

**Comment by gurumark** [comment]
@michaelwittig  Thanks for the response. I get that. 
I think I can live with CF console which provides these parameters by default in updates. That's not my issue right now. Whatever I do I cannot apply the updates to the stack. I am trying to change some php.ini values but no luck. I do not know how to debug since there is no information. 
I know it is another issue not related to this tool. If you provide some hints, I will greatly appreciate.
